run:
  timeout: 5m
  tests: true

output:
  format: colored-line-number

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: forgor
  govet:
    check-shadowing: true
  misspell:
    locale: US

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - misspell
    - ineffassign
    - unused
    - typecheck
    - errcheck
  disable-all: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
