package cmd

import (
	"fmt"

	"forgor/internal/config"

	"github.com/spf13/cobra"
)

// lastCmd represents the last command
var lastCmd = &cobra.Command{
	Use:   "last",
	Short: "Show the last generated command",
	Long: `Display the last command generated by forgor without executing it.

This is useful to see what command was previously generated before deciding to run it.

Examples:
  forgor last                            # Show the last generated command
  forgor last | pbcopy                   # Copy last command to clipboard (macOS)`,
	RunE: func(cmd *cobra.Command, args []string) error {
		command, err := config.LoadLastCommand()
		if err != nil {
			return err
		}

		fmt.Printf("%s\n", command)
		return nil
	},
}

func init() {
	rootCmd.AddCommand(lastCmd)
}
