# forgor configuration file
# Copy this to ~/.config/forgor/config.yaml and customize as needed

default_profile: "openai"

profiles:
  # OpenAI configuration
  openai:
    provider: "openai"
    api_key: "${OPENAI_API_KEY}" # Set OPENAI_API_KEY environment variable
    model: "gpt-4"
    max_tokens: 150
    temperature: 0.1

  # Google AI Gemini configuration
  gemini:
    provider: "gemini"
    api_key: "${GOOGLE_AI_API_KEY}" # Set GOOGLE_AI_API_KEY environment variable
    model: "gemini-1.5-pro"
    max_tokens: 150
    temperature: 0.1

  # Local model configuration (e.g., Ollama)
  local:
    provider: "local"
    endpoint: "http://localhost:11434" # Ollama default endpoint
    model: "codellama"
    max_tokens: 150

  # Anthropic Claude configuration
  anthropic:
    provider: "anthropic"
    api_key: "${ANTHROPIC_API_KEY}" # Set ANTHROPIC_API_KEY environment variable
    model: "claude-3-sonnet-20240229"
    max_tokens: 150
    temperature: 0.1

history:
  max_commands: 10
  shells: ["bash", "zsh", "fish"]

security:
  redact_sensitive: true
  filters:
    - "password"
    - "token"
    - "secret"
    - "key"
    - "api_key"

output:
  format: "plain" # plain, json, interactive
  confirm_before_run: false
